CREATE DATABASE IF NOT EXISTS Balance DEFAULT CHARACTER SET latin1 COLLATE latin1_bin;

GRANT ALL PRIVILEGES ON Balance.* TO 'user'@'server' IDENTIFIED BY 'passwort';

use Balance;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS BAL_BANKACCOUNT;
DROP TABLE IF EXISTS BAL_INSTITUTION;
DROP TABLE IF EXISTS BAL_COMPANY;
DROP TABLE IF EXISTS BAL_LOCATION;
DROP TABLE IF EXISTS BAL_INCOME;
DROP TABLE IF EXISTS BAL_BALANCE;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `BAL_LOCATION` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `CREATED_AT` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1

CREATE TABLE `BAL_INSTITUTION` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `LOCATION_ID` int(10) NOT NULL,
  `CREATED_AT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `LOCATION_ID` (`LOCATION_ID`),
  CONSTRAINT `BAL_INSTITUTION_ibfk_1` FOREIGN KEY (`LOCATION_ID`) REFERENCES `BAL_LOCATION` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1

CREATE TABLE `BAL_BANKACCOUNT` (
  `BNR` varchar(50) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `INST_ID` int(10) NOT NULL,
  `CREATED_AT` datetime NOT NULL,
  PRIMARY KEY (`BNR`),
  KEY `INST_ID` (`INST_ID`),
  CONSTRAINT `BAL_BANKACCOUNT_ibfk_1` FOREIGN KEY (`INST_ID`) REFERENCES `BAL_INSTITUTION` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE `BAL_COMPANY` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `LOCATION_ID` int(10) NOT NULL,
  `CREATED_AT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `LOCATION_ID` (`LOCATION_ID`),
  CONSTRAINT `BAL_COMPANY_ibfk_1` FOREIGN KEY (`LOCATION_ID`) REFERENCES `BAL_LOCATION` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1

CREATE TABLE `BAL_BALANCE` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `MONTH` int(10) NOT NULL,
  `YEAR` int(10) NOT NULL,
  `BNR` varchar(50) NOT NULL,
  `BALANCE` decimal(10,2) NOT NULL,
  `AVAILABLE_BALANCE` decimal(10,2) NOT NULL,
  `UNAVAILABLE_BALANCE` decimal(10,2) NOT NULL,
  `DATE_CHECKED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UC_Balance` (`MONTH`,`YEAR`,`BNR`),
  KEY `BNR` (`BNR`),
  CONSTRAINT `BAL_BALANCE_ibfk_1` FOREIGN KEY (`BNR`) REFERENCES `BAL_BANKACCOUNT` (`BNR`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1

CREATE TABLE `BAL_INCOME` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` int(10) NOT NULL,
  `MONTH` int(2) NOT NULL,
  `YEAR` int(4) NOT NULL,
  `INCOME` decimal(10,2) NOT NULL,
  `STATUTORY_LEVIES` decimal(10,2) NOT NULL,
  `NET_INCOME` decimal(10,2) NOT NULL,
  `CREATED_AT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UC_INCOME` (`COMPANY_ID`,`MONTH`,`YEAR`),
  KEY `BAL_INCOME_ibfk_1_idx` (`COMPANY_ID`),
  CONSTRAINT `BAL_INCOME_ibfk_1` FOREIGN KEY (`COMPANY_ID`) REFERENCES `BAL_COMPANY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1